// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Debug: typeof import('./src/components/debug.vue')['default']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    Loading: typeof import('./src/components/loading.vue')['default']
  }
}

export { }
